# Generated by Django 5.1.3 on 2024-12-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=510)),
                ('date', models.DateField()),
                ('postBody', models.CharField(max_length=10000)),
            ],
        ),
    ]
