# Generated by Django 5.1.3 on 2024-12-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_post_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('githubLink', models.URLField(max_length=128)),
            ],
        ),
    ]
